{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "portal.fullname" . }}-leader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "portal.fullname" . }}-leader
subjects:
  - kind: ServiceAccount
    name: {{ include "portal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
