apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" .Release.Namespace (include "portal.fullname" .) | quote }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
