package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// newDocgenCmd renders the cobra command tree as Markdown. With no flags the
// command tree is concatenated into docs/reference/cli.md. With --dir it
// emits one file per subcommand (the standard cobra/doc layout).
//
// The command is Hidden because it isn't intended for operators — it's a
// build-tool subcommand consumed by `make generate-docs` and the docs-drift
// CI gate.
func newDocgenCmd() *cobra.Command {
	var (
		out string
		dir string
	)
	cmd := &cobra.Command{
		Use:    "docgen",
		Short:  "Generate CLI reference Markdown for docs/reference/cli.md",
		Hidden: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			root := cmd.Root()
			if dir != "" {
				if err := os.MkdirAll(dir, 0o755); err != nil {
					return err
				}
				// linkHandler/filePrepender are required by cobra/doc; we
				// keep them minimal so output is portable to mkdocs and to
				// raw GitHub rendering.
				link := func(name string) string { return name }
				prefix := func(name string) string {
					base := strings.TrimSuffix(filepath.Base(name), ".md")
					return fmt.Sprintf("# `%s`\n\n", strings.ReplaceAll(base, "_", " "))
				}
				return doc.GenMarkdownTreeCustom(root, dir, prefix, link)
			}

			var w io.Writer = cmd.OutOrStdout()
			if out != "" {
				f, err := os.Create(out)
				if err != nil {
					return err
				}
				defer f.Close()
				w = f
			}
			return renderTreeFlat(w, root)
		},
	}
	cmd.Flags().StringVar(&out, "out", "", "write concatenated Markdown to this file (default stdout)")
	cmd.Flags().StringVar(&dir, "dir", "", "write one Markdown file per subcommand into this directory (overrides --out)")
	return cmd
}

// renderTreeFlat writes every subcommand's Markdown to w with H2 dividers.
// Order is alphabetical so the output is deterministic for the docs-drift CI
// gate.
func renderTreeFlat(w io.Writer, root *cobra.Command) error {
	cmds := flatten(root)
	sort.SliceStable(cmds, func(i, j int) bool { return cmds[i].CommandPath() < cmds[j].CommandPath() })
	fmt.Fprintln(w, "# Portal CLI reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Auto-generated by `portal docgen`. Do not edit by hand — run `make generate-docs` to refresh.")
	fmt.Fprintln(w)
	for _, c := range cmds {
		fmt.Fprintf(w, "## `%s`\n\n", c.CommandPath())
		if err := doc.GenMarkdown(c, w); err != nil {
			return err
		}
		fmt.Fprintln(w)
	}
	return nil
}

// flatten returns every command in the tree (root + descendants) except those
// flagged Hidden — docgen, completion, help.
func flatten(c *cobra.Command) []*cobra.Command {
	if c.Hidden {
		return nil
	}
	out := []*cobra.Command{c}
	for _, sub := range c.Commands() {
		out = append(out, flatten(sub)...)
	}
	return out
}
